### PR TITLE
WebAPI integration

### PR DESCRIPTION
**Pull request by Mikhail-iontsev**
Closes https://github.com/OHDSI/Ares/issues/183

WebAPI settings are located in the env folder. Cross-origin is supported if your WebAPI instance is configured to allow such requests.

To point the app to your WebAPI instance, please change the "WEB_API_URL" variable in the env.json file (no need to rebuild the app after that).

To authenticate please indicate your azure domain and client id in the env.json file.

### CODE REVIEW

**Comment by fdefalco** [comment]
Getting the following error after updating the env.json file with the following settings:

{
  "WEB_API_URL": "https://epi.jnj.com:8443/WebAPI",
  "WEB_API_ENABLED": "true",
  "AZURE_AUTH_DOMAIN": "",
  "AZURE_CLIENT_ID": ""
}

image

Do I need settings for the 3rd and 4th property?

**Comment by Mikhail-iontsev** [comment]
Yes, for the auth to work you'll need to specify your client id (for that you need to register the app in Azure dashboard) and your auth domain (also found there).

I'm still trying to understand how the domain auth works, but it doesn't seem to work in all cases (depends on the browser and the OS version)

**Comment by fdefalco** [comment]
Ok, we aren't on an Azure hosted domain.  I can demo the issue for you tomorrow on our status call.

**Comment by fdefalco** [comment]
@Mikhail-iontsev  per our discussion:

- [ ] modify font size in drop down from 16 to 12 to be consistent with UI
- [ ] change spacing in concept results table to be 'dense' 
- [ ] make columns sortable
- [ ] limit results to standard concept (STANDARD_CONCEPT == S)

**Comment by Mikhail-iontsev** [comment]
"modify font size in drop down from 16 to 12 to be consistent with UI" - it would be better to create a separate task as changes should be made in all reports using the v-data-table component.

**Comment by fdefalco** [comment]
@Mikhail-iontsev sorry that I let this get stale..  Can you update to merge to the new develop branch with the vue 3.0 transition?

**Review by fdefalco — APPROVED** [review]

**Pull request merged**
