### PR TITLE
Add tooltip and resize to measurement record count proportion chart

### PR DESCRIPTION
**Pull request by Mikhail-iontsev**
Closes https://github.com/OHDSI/Ares/issues/39

Added interactivity and tooltip to the report. 

The ruler will change its position in all of the reports at the same time, the tooltip will show only for the one in focus. 

Legend can filter out data depending on what's currently in focus. 

The charts are now aligned vertically and stretched to container width.

### CODE REVIEW

**Comment by fdefalco** [comment]
Can you reduce the size of the age decile plots to say 30px instead of 150 and reduce the spacing between each decile to say 5.   As it is, it takes up too much vertical space.

**Comment by fdefalco** [comment]
resizing the window causes issues with overlap of v-card component and the chart

image

**Comment by Mikhail-iontsev** [comment]
> resizing the window causes issues with overlap of v-card component and the chart
> 
> image

The problem seems to be that responsiveness and facets do not get along well. The most popular scenario could be solved by adding autosize: { resize: true}, but overflowing is still inevitable if the browser window is too narrow.

**Comment by Mikhail-iontsev** [comment]
Spacing increased to 10px as some larger values get squished together making it difficult to read.

**Pull request merged**
