### PR TITLE
Update DomainTable.vue

### PR DESCRIPTION
**Pull request by fdefalco**
Added the function to AresIndexer to generate the new data files.

https://github.com/OHDSI/AresIndexer/commit/b609bb69ccca608e7dc02268939f2948d467f3b8

Run AresIndexer::computeCharacterizationDifference(sourceFolders) to generate the files in your environment and test.

### CODE REVIEW

**Comment by Mikhail-iontsev** [comment]
I managed to generate the files and it seems to be working great in the UI, but I had to update the AresIndexer Namespace file to include the new function and change the @name case to camelCase (I was getting an error otherwise when I tried to install the package)

**Review by Mikhail-iontsev — APPROVED** [review]
Ok

**Comment by Mikhail-iontsev** [comment]
Screenshot 2023-03-03 at 02 12 09
There are also values displayed even though it's the first release of the source. Not sure where that is coming from.

**Comment by fdefalco** [comment]
Yes, that sounds better.

**Comment by fdefalco** [comment]
@Mikhail-iontsev Can you make the change you suggested and then merge this PR? Thanks!

**Pull request merged**
